#!/usr/bin/env python3
"""
deploy.py - Automated deployment script for AI Memory Layer

Usage:
    python deploy.py setup           # Setup environment
    python deploy.py local          # Deploy locally with Docker
    python deploy.py test            # Test deployment
    python deploy.py clean           # Clean up containers
"""

import os
import sys
import subprocess
import secrets
from pathlib import Path

# Colors (Windows compatible)
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
NC = "\033[0m"

def run_cmd(cmd, capture=True):
    """Run shell command."""
    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=capture, text=True
        )
        return result.returncode == 0, result.stdout, result.stderr
    except Exception as e:
        return False, "", str(e)

def print_success(msg):
    print(f"{GREEN}[OK] {msg}{NC}")

def print_error(msg):
    print(f"{RED}[ERROR] {msg}{NC}")

def print_info(msg):
    print(f"{BLUE}[INFO] {msg}{NC}")

def print_warn(msg):
    print(f"{YELLOW}[WARN] {msg}{NC}")

def setup():
    """Setup environment and generate secrets."""
    print_info("Setting up environment...")

    secret_key = secrets.token_hex(32)

    env_content = f'''# Production Environment Variables
# Generated by deploy.py

# OpenAI API Key (get from https://platform.openai.com/api-keys)
OPENAI_API_KEY=sk-YOUR-KEY-HERE

# Database Connection (from Supabase or Render PostgreSQL)
# Format: postgresql+asyncpg://user:password@host:5432/database
DATABASE_URL=postgresql+asyncpg://postgres:password@localhost:5432/ai_memory

# Secret key for JWT tokens
SECRET_KEY={secret_key}

# Environment
ENVIRONMENT=production

# CORS (your frontend domain, or * for all)
ALLOWED_ORIGINS=*

# Demo mode (false for production)
DEMO_MODE=false
'''

    env_file = Path(".env.production")
    if env_file.exists():
        print_warn(".env.production already exists")
        response = input("Overwrite? (y/N): ")
        if response.lower() != 'y':
            print_info("Keeping existing .env.production")
            return

    with open(env_file, "w") as f:
        f.write(env_content)

    print_success("Created .env.production")
    print("")
    print_info("Please edit .env.production with your values:")
    print("  - OPENAI_API_KEY (from platform.openai.com)")
    print("  - DATABASE_URL (from Supabase/Render)")
    print("  - SECRET_KEY is already generated")
    print("")
    print_info(f"Generated SECRET_KEY: {secret_key[:8]}...{secret_key[-8:]}")

def deploy_local():
    """Deploy locally with Docker Compose."""
    print_info("Deploying locally with Docker Compose...")

    # Check Docker
    success, stdout, stderr = run_cmd("docker --version")
    if not success:
        print_error("Docker not found. Please install Docker Desktop.")
        print_error("Download: https://www.docker.com/products/docker-desktop")
        return

    # Load environment
    if Path(".env.production").exists():
        print_info("Using .env.production...")
    else:
        print_warn("No .env.production found. Using defaults.")

    print_info("Building containers..."
    )
    success, stdout, stderr = run_cmd("docker-compose -f docker-compose.prod.yml build")
    if not success:
        print_error("Build failed:")
        print_error(stderr)
        return

    print_info("Starting services...")
    success, stdout, stderr = run_cmd("docker-compose -f docker-compose.prod.yml up -d")
    if not success:
        print_error("Failed to start services:")
        print_error(stderr)
        return

    print_success("Local deployment complete!")
    print("")
    print_info("Services:")
    print("  Backend:  http://localhost:8000")
    print("  Frontend: http://localhost:8501")
    print("  API Docs: http://localhost:8000/docs")

def test_deployment():
    """Test deployment health."""
    import requests
    import time

    print_info("Testing deployment...")

    backend_url = os.environ.get("BACKEND_URL", "http://localhost:8000")

    # Health check
    try:
        resp = requests.get(f"{backend_url}/health/live", timeout=5)
        if resp.status_code == 200:
            print_success("✓ /health/live OK")
        else:
            print_error(f"✗ /health/live returned {resp.status_code}")
    except Exception as e:
        print_error(f"✗ /health/live FAILED: {e}")

    time.sleep(1)

    # Ready check
    try:
        resp = requests.get(f"{backend_url}/health/ready", timeout=5)
        data = resp.json()
        print_success(f"✓ /health/ready: {data.get('status', 'unknown')}")
        if "checks" in data:
            for check, status in data["checks"].items():
                if status == "ok":
                    print_success(f"  - {check}: OK")
                else:
                    print_warn(f"  - {check}: {status}")
    except Exception as e:
        print_warn(f"⚠ /health/ready: {e}")

    # Register test
    try:
        resp = requests.post(
            f"{backend_url}/api/v1/auth/register",
            json={"email": "test@test.com", "password": "test123"},
            timeout=5
        )
        if resp.status_code in [200, 201]:
            print_success("✓ /api/v1/auth/register OK")
        else:
            print_warn(f"⚠ /api/v1/auth/register: {resp.status_code}")
    except Exception as e:
        print_error(f"✗ /api/v1/auth/register FAILED: {e}")

    print("")

def clean():
    """Clean up containers."""
    print_info("Cleaning up containers...")
    run_cmd("docker-compose -f docker-compose.prod.yml down -v", capture=False)
    print_success("Cleanup complete!")

def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "help"

    commands = {
        "setup": setup,
        "local": deploy_local,
        "test": test_deployment,
        "clean": clean,
    }

    if cmd == "help":
        print("""
AI Memory Layer - Deployment Script

Usage:
    python deploy.py setup    # Setup environment and generate secrets
    python deploy.py local     # Deploy locally with Docker Compose
    python deploy.py test      # Test deployment health
    python deploy.py clean      # Clean up containers

Requirements:
    - Docker & Docker Compose installed
    - OpenAI API key from platform.openai.com
    - PostgreSQL database (Supabase or Render)
        """)
    elif cmd in commands:
        commands[cmd]()
    else:
        print_error(f"Unknown command: {cmd}")
        print("Run 'python deploy.py help' for usage")

if __name__ == "__main__":
    main()