#!/bin/bash
# deploy.sh - Automated deployment script for AI Memory Layer

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo_error() { echo -e "${RED}ERROR: $1${NC}"; }
echo_success() { echo -e "${GREEN}SUCCESS: $1${NC}"; }
echo_info() { echo -e "${BLUE}INFO: $1${NC}"; }
echo_warn() { echo -e "${YELLOW}WARNING: $1${NC}"; }

# ==========================================
# CONFIGURATION
# ==========================================

PROJECT_NAME="ai-memory-layer"
FRONTEND_DIR="frontend"

# Default values
RENDER_API_KEY=""
RENDER_SERVICE_NAME="ai-memory-frontend"
STREAMLIT_CLOUD_REPO=""

# ==========================================
# FUNCTIONS
# ==========================================

show_help() {
    cat << EOF
Usage: ./deploy.sh [COMMAND] [OPTIONS]

Commands:
    setup          Setup environment and generate secrets
    local          Deploy locally with Docker Compose
    render         Deploy backend to Render
    streamlit      Deploy frontend to Streamlit Cloud
    full           Full deployment (backend + frontend + database)
    test           Test deployment
    clean          Clean up local containers

Options:
    --api-key KEY      Render API key
    --service NAME    Render service name
    --repo REPO        GitHub repo (user/repo)
    -h, --help        Show this help

Examples:
    ./deploy.sh setup
    ./deploy.sh local
    ./deploy.sh full --api-key YOUR_RENDER_KEY --repo yourname/memorylayer
    ./deploy.sh test

EOF
}

generate_secrets() {
    echo_info "Generating SECRET_KEY..."
    SECRET_KEY=$(python -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null)
    echo "Generated SECRET_KEY: ${SECRET_KEY:0:8}...${SECRET_KEY: -8}"
    echo ""
    echo "Add these to your .env.production:"
    echo "SECRET_KEY=${SECRET_KEY}"
    echo "OPENAI_API_KEY=sk-..."
    echo "DATABASE_URL=<set from Supabase/Render secret dashboard>"
}

setup_env() {
    echo_info "Setting up environment..."

    if [ -f ".env.production" ]; then
        echo_warn ".env.production already exists"
        read -p "Overwrite? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo_info "Keeping existing .env.production"
            return
        fi
    fi

    cat > .env.production << 'EOF'
# Production Environment Variables
# Generated by deploy.sh
# Keep this file out of git. DATABASE_URL must come from your secret manager
# or local shell environment; never commit a real database URL.

# OpenAI API Key (get from https://platform.openai.com/api-keys)
OPENAI_API_KEY=sk-YOUR-KEY-HERE

# Database Connection (required)
# Format: postgresql+asyncpg://<user>:<url-encoded-password>@<host>:6543/postgres?sslmode=require
DATABASE_URL=

# Secret key for JWT tokens (generate with: python -c "import secrets; print(secrets.token_hex(32))")
SECRET_KEY=CHANGE-ME-IN-PRODUCTION

# Environment
ENVIRONMENT=production

# CORS (comma-separated trusted frontend origins; never use * in production)
ALLOWED_ORIGINS=https://your-frontend.example

# Demo mode (false for production)
DEMO_MODE=false
EOF

    echo_success "Created .env.production"
    echo ""
    echo_info "Please edit .env.production with your values:"
    echo "  - OPENAI_API_KEY (from platform.openai.com)"
    echo "  - DATABASE_URL (from Supabase/Render secret dashboard; leave blank until set)"
    echo "  - SECRET_KEY (already generated)"
}

deploy_local() {
    echo_info "Deploying locally with Docker Compose..."

    # Check Docker
    if ! command -v docker &> /dev/null; then
        echo_error "Docker not found. Please install Docker first."
        exit 1
    fi

    if ! command -v docker-compose &> /dev/null; then
        echo_error "docker-compose not found. Please install Docker Compose first."
        exit 1
    fi

    # Load environment
    if [ -f ".env.production" ]; then
        echo_info "Loading environment from .env.production..."
        set -a
        source .env.production
        set +a
    else
        echo_warn "No .env.production found. Using defaults."
    fi

    # Build and start
    echo_info "Building containers..."
    docker-compose -f docker-compose.prod.yml build

    echo_info "Starting services..."
    docker-compose -f docker-compose.prod.yml up -d

    echo_success "Local deployment complete!"
    echo ""
    echo_info "Services:"
    echo "  Backend:  http://localhost:8000"
    echo "  Frontend: http://localhost:8501"
    echo ""

    # Health check
    echo_info "Running health checks..."
    sleep 5

    BACKEND_HEALTH=$(curl -s http://localhost:8000/health/live 2>/dev/null || echo "{}")
    if echo "$BACKEND_HEALTH" | grep -q "ok"; then
        echo_success "Backend health: OK"
    else
        echo_warn "Backend health: FAILED (may need a moment)"
    fi

    FRONTEND_HEALTH=$(curl -s http://localhost:8501 2>/dev/null || echo "error")
    if [ "$FRONTEND_HEALTH" != "error" ]; then
        echo_success "Frontend health: OK"
    else
        echo_warn "Frontend health: FAILED (may need a moment)"
    fi
}

deploy_render() {
    if [ -z "$RENDER_API_KEY" ]; then
        echo_error "Render API key required. Use --api-key or set RENDER_API_KEY env var"
        exit 1
    fi

    echo_info "Deploying to Render..."

    # Check if gh CLI is available
    if ! command -v gh &> /dev/null; then
        echo_error "GitHub CLI (gh) not found. Please install from https://cli.github.com/"
        exit 1
    fi

    # Create Render app
    curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
         -H "Content-Type: application/json" \
         -d '{"name":"'"$RENDER_SERVICE_NAME"'","region":"Oregon"}' \
         https://api.render.com/v1/web-services || echo

    echo_success "Render deployment initiated!"
    echo ""
    echo_info "Next steps:"
    echo "  1. Go to https://dashboard.render.com"
    echo "  2. Configure environment variables in the service settings"
    echo "  3. Add your DATABASE_URL, OPENAI_API_KEY, SECRET_KEY"
    echo "  4. Deploy will trigger automatically on git push"
}

deploy_streamlit() {
    echo_info "Deploying to Streamlit Cloud..."

    if [ -z "$STREAMLIT_CLOUD_REPO" ]; then
        echo_error "GitHub repo required. Use --repo or set STREAMLIT_CLOUD_REPO"
        exit 1
    fi

    echo_info "Streamlit Cloud deployment requires:"
    echo "  1. Connect your repo at https://share.streamlit.io"
    echo "  2. Select '$FRONTEND_DIR' as the frontend folder"
    echo "  3. Add in app settings:"
    echo "     API_BASE_URL = https://your-backend.onrender.com"
    echo ""

    echo_info "Alternatively, deploy via Docker:"
    echo "  docker build -t ai-memory-frontend ./frontend"
    echo "  docker run -p 8501:8501 -e API_BASE_URL=\$API_BASE_URL ai-memory-frontend"

    echo_success "Streamlit Cloud setup ready!"
}

test_deployment() {
    echo_info "Testing deployment..."

    BACKEND_URL="${BACKEND_URL:-http://localhost:8000}"

    echo "Testing backend endpoints..."

    # Health check
    if curl -s "$BACKEND_URL/health/live" | grep -q "ok"; then
        echo_success "✓ /health/live OK"
    else
        echo_error "✗ /health/live FAILED"
    fi

    # Ready check
    READY_RESPONSE=$(curl -s "$BACKEND_URL/health/ready")
    if echo "$READY_RESPONSE" | grep -q "ready\|degraded"; then
        echo_success "✓ /health/ready OK"
    else
        echo_warn "⚠ /health/ready may need database"
    fi

    # Register endpoint (will fail if no DB, but tests auth)
    REGISTER_RESPONSE=$(curl -s -X POST "$BACKEND_URL/api/v1/auth/register" \
        -H "Content-Type: application/json" \
        -d '{"email":"test@test.com","password":"test123"}')

    if echo "$REGISTER_RESPONSE" | grep -qE "id|error"; then
        echo_success "✓ /api/v1/auth/register OK"
    else
        echo_warn "⚠ /api/v1/auth/register: $REGISTER_RESPONSE"
    fi

    echo ""
    echo_success "Tests complete!"
}

clean_local() {
    echo_info "Cleaning up local containers..."
    docker-compose -f docker-compose.prod.yml down -v 2>/dev/null || true
    docker system prune -f 2>/dev/null || true
    echo_success "Cleanup complete!"
}

# ==========================================
# MAIN
# ==========================================

# Parse arguments
COMMAND="${1:-help}"
shift || true

case "$COMMAND" in
    setup)
        generate_secrets
        setup_env
        ;;
    local)
        deploy_local
        test_deployment
        ;;
    render)
        deploy_render
        ;;
    streamlit)
        deploy_streamlit
        ;;
    full)
        setup_env
        deploy_local
        echo ""
        deploy_streamlit
        ;;
    test)
        test_deployment
        ;;
    clean)
        clean_local
        ;;
    help|-h|--help)
        show_help
        ;;
    *)
        echo_error "Unknown command: $COMMAND"
        show_help
        exit 1
        ;;
esac
