"""Tests for the nexmem-admin CLI (P11-I1, Block 6).

Four tests covering the four operator-facing commands. Tests call
the command functions directly (not via subprocess) and capture
stdout via pytest's ``capsys`` so the CLI surface can be exercised
without a separate Python interpreter and without needing a real
Postgres / Redis. All tests run under ``DEMO_MODE=true`` (set by
``tests/conftest.py``).

Sensitive-field exposure check (test #3) is the most important
test in this file — ``show-user`` is the natural place to leak a
password hash or TOTP secret if the implementation grows over
time, and an automated assertion is the only way to keep that
honest as the user model evolves.
"""
from __future__ import annotations

import argparse
import re
import uuid

import pytest

from app import demo_db
from app.core import demo_auth
from app.core.audit_log import (
    list_demo_auth_events,
    reset_demo_audit_log,
)
from scripts.nexmem_admin import (
    cmd_force_revoke_key,
    cmd_list_users,
    cmd_rotate_secret_key,
    cmd_show_user,
)


pytestmark = [pytest.mark.unit]


@pytest.fixture(autouse=True)
def _reset_audit():
    """Tests in this file inspect the audit-log demo store directly;
    reset it so cross-test bleed cannot make a passing test fake."""
    reset_demo_audit_log()
    yield
    reset_demo_audit_log()


# ── 1 ─────────────────────────────────────────────────────────────────────────
def test_rotate_secret_key_prints_new_key(capsys):
    """``rotate-secret-key`` prints a 64-char hex value plus the
    operator-facing instructions, and returns 0."""
    rc = cmd_rotate_secret_key(argparse.Namespace())
    assert rc == 0

    out = capsys.readouterr().out
    match = re.search(r"NEW_SECRET_KEY=([0-9a-f]+)", out)
    assert match, f"NEW_SECRET_KEY line not in output:\n{out}"
    assert len(match.group(1)) == 64, "must be 64 hex chars (32 bytes)"

    # The "this invalidates every JWT" warning MUST be visible — without
    # it an operator might rotate the key without expecting the logout
    # storm and panic.
    lower = out.lower()
    assert "invalidate" in lower
    assert "redeploy" in lower
    # And we must explicitly say we did NOT auto-rotate.
    assert "auto-rotation" in lower or "do not auto-rotate" in lower or \
        "not auto-rotate" in lower or "intentionally not" in lower


# ── 2 ─────────────────────────────────────────────────────────────────────────
def test_list_users_masks_email(capsys):
    """``list-users`` shows every user once, and EVERY printed email
    is masked. The full address never appears anywhere in stdout."""
    a = demo_auth.create_user(
        email="alice@nexmem.example.com",
        wallet_address=None,
        hashed_password="hashed-alice",
    )
    b = demo_auth.create_user(
        email="bob@nexmem.example.com",
        wallet_address=None,
        hashed_password="hashed-bob",
    )

    rc = cmd_list_users(argparse.Namespace(limit=50))
    assert rc == 0

    out = capsys.readouterr().out
    # Both users present (by id).
    assert str(a.id) in out
    assert str(b.id) in out
    # Both masks present.
    assert "a***@nexmem.example.com" in out
    assert "b***@nexmem.example.com" in out
    # Neither full address present.
    assert "alice@nexmem.example.com" not in out
    assert "bob@nexmem.example.com" not in out
    # Header is printed exactly once.
    assert out.count("user_id") == 1


# ── 3 ─────────────────────────────────────────────────────────────────────────
def test_show_user_never_exposes_sensitive_fields(capsys):
    """``show-user`` must never print ``hashed_password``, ``totp_secret``,
    or any raw API key. This is the canary for accidental leaks added
    by future field additions to the user model."""
    secret_password_hash = "bcrypt$$$DO-NOT-LEAK-PASSWORD-HASH"
    secret_totp = "JBSWY3DPEHPK3PXP-DO-NOT-LEAK"

    user = demo_auth.create_user(
        email="canary@nexmem.example.com",
        wallet_address=None,
        hashed_password=secret_password_hash,
    )
    # Stamp the totp secret directly; the helper exists for the TOTP
    # router but here we want the store populated for the CLI to read.
    demo_db.demo_users[str(user.id)]["totp_secret"] = secret_totp
    demo_db.demo_users[str(user.id)]["totp_enabled"] = True

    # Add an API key — its raw value is generated by the auth router,
    # but we simulate the stored hash to confirm neither hash nor
    # any synthetic raw value reaches stdout.
    demo_auth.add_api_key(user.id, "deadbeef" * 8, "telegram-bot")

    rc = cmd_show_user(argparse.Namespace(user_id=str(user.id)))
    assert rc == 0

    out = capsys.readouterr().out
    # Sanity: the panel actually printed.
    assert str(user.id) in out
    assert "c***@nexmem.example.com" in out
    assert "totp_enabled" in out
    assert "active_api_key_count" in out

    # Forbidden substrings.
    assert secret_password_hash not in out
    assert "hashed_password" not in out
    assert secret_totp not in out
    assert "totp_secret" not in out
    assert "deadbeef" not in out  # the api_key hash literal
    # Belt-and-braces — never echo the unmasked email either.
    assert "canary@nexmem.example.com" not in out


# ── 4 ─────────────────────────────────────────────────────────────────────────
def test_force_revoke_key_in_demo_mode(capsys):
    """``force-revoke-key`` flips ``is_active=False`` on the key
    and writes an ``admin_force_revoke_api_key`` audit row."""
    user = demo_auth.create_user(
        email="ops@nexmem.example.com",
        wallet_address=None,
        hashed_password="hashed",
    )
    key = demo_auth.add_api_key(user.id, "x" * 64, "soon-to-die")
    assert demo_db.demo_api_keys[str(key.id)]["is_active"] is True

    rc = cmd_force_revoke_key(argparse.Namespace(key_id=str(key.id)))
    assert rc == 0

    out = capsys.readouterr().out
    assert f"Key {key.id} revoked" in out

    # Side effects.
    assert demo_db.demo_api_keys[str(key.id)]["is_active"] is False
    events = list_demo_auth_events(str(user.id))
    actions = [e["action"] for e in events]
    assert "admin_force_revoke_api_key" in actions
    last = next(e for e in events if e["action"] == "admin_force_revoke_api_key")
    assert last["payload"]["api_key_id"] == str(key.id)
    assert last["payload"]["actor"] == "admin"

    # An unknown key id returns exit 1 and stays out of the audit log.
    audit_count_before = len(list_demo_auth_events(str(user.id)))
    rc2 = cmd_force_revoke_key(argparse.Namespace(key_id=str(uuid.uuid4())))
    assert rc2 == 1
    assert len(list_demo_auth_events(str(user.id))) == audit_count_before
