"""Extend RLS coverage to users, api_keys, token_usage (R-H7).

Revision ID: 013_rls_users_apikeys_tokenusage
Revises: 012_add_app_id_to_engrams
Create Date: 2026-05-22

Threat-model decisions (documented in BACKEND_HARDENING_PHASE2.md §P2-C4):

  users
    - SELECT  → permissive (`USING (true)`).
        Justification: the email/id pair must remain readable
        pre-authentication so login can find the user by email and so
        the API-key-auth path can resolve user_id → User without
        chicken-and-egg. The data on the row is not high-sensitivity;
        the bcrypt password hash is not exfiltratable in any
        practical sense and the threat that matters is *modification*,
        not enumeration.
    - INSERT  → permissive (`WITH CHECK (true)`).
        Anyone can register a new user; the row's id is freshly
        generated by the application.
    - UPDATE  → self-only (`id = current_setting('app.current_user_id')`).
    - DELETE  → self-only.

  api_keys
    - SELECT  → permissive (`USING (true)`).
        Justification: the API-key auth flow looks up a row by
        `key_hash` BEFORE the user is identified. The row stores a
        SHA-256 hash, not the raw key; reading the hash does not
        enable forgery. UPDATE / DELETE are still self-only, so
        cross-user revocation is impossible.
    - INSERT  → self-only (`WITH CHECK (user_id = GUC)`).
        Closes the "can a session create an API key for another
        user?" path even if the application forgets the check.
    - UPDATE/DELETE → self-only.

  token_usage
    - All operations → self-only.
        This table is never read pre-authentication; no special case
        needed.

All three tables use `ENABLE ROW LEVEL SECURITY` AND
`FORCE ROW LEVEL SECURITY`, matching migration 008 for memory
tables, so even the table owner (the app's Postgres role) obeys
the policies.

`current_setting('app.current_user_id', true)` returns '' when
unset; we cast via `NULLIF(...)::uuid` so unset GUC produces NULL,
and the per-row predicate `id = NULL` is false (PostgreSQL three-
valued logic) — i.e. a session without GUC can still SELECT
(permissive policy) but cannot UPDATE / DELETE / INSERT into a
specific user's row.

This migration is non-destructive and idempotent on re-run.
"""

from alembic import op


revision = "013_rls_users_apikeys_tokenusage"
down_revision = "012_add_app_id_to_engrams"
branch_labels = None
depends_on = None


_GUC = "NULLIF(current_setting('app.current_user_id', true), '')::uuid"


def _enable_force(table: str) -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")


def _drop_policy(table: str, name: str) -> None:
    op.execute(f"DROP POLICY IF EXISTS {name} ON {table}")


def upgrade() -> None:
    # ── users ────────────────────────────────────────────────────────────
    _enable_force("users")
    _drop_policy("users", "users_select_all")
    op.execute(
        "CREATE POLICY users_select_all ON users FOR SELECT USING (true)"
    )
    _drop_policy("users", "users_insert_open")
    op.execute(
        "CREATE POLICY users_insert_open ON users FOR INSERT WITH CHECK (true)"
    )
    _drop_policy("users", "users_update_self")
    op.execute(
        f"CREATE POLICY users_update_self ON users "
        f"FOR UPDATE USING (id = {_GUC}) WITH CHECK (id = {_GUC})"
    )
    _drop_policy("users", "users_delete_self")
    op.execute(
        f"CREATE POLICY users_delete_self ON users FOR DELETE USING (id = {_GUC})"
    )

    # ── api_keys ─────────────────────────────────────────────────────────
    _enable_force("api_keys")
    _drop_policy("api_keys", "api_keys_select_all")
    op.execute(
        "CREATE POLICY api_keys_select_all ON api_keys FOR SELECT USING (true)"
    )
    _drop_policy("api_keys", "api_keys_insert_self")
    op.execute(
        f"CREATE POLICY api_keys_insert_self ON api_keys "
        f"FOR INSERT WITH CHECK (user_id = {_GUC})"
    )
    _drop_policy("api_keys", "api_keys_update_self")
    op.execute(
        f"CREATE POLICY api_keys_update_self ON api_keys "
        f"FOR UPDATE USING (user_id = {_GUC}) WITH CHECK (user_id = {_GUC})"
    )
    _drop_policy("api_keys", "api_keys_delete_self")
    op.execute(
        f"CREATE POLICY api_keys_delete_self ON api_keys "
        f"FOR DELETE USING (user_id = {_GUC})"
    )

    # ── token_usage ──────────────────────────────────────────────────────
    _enable_force("token_usage")
    _drop_policy("token_usage", "token_usage_self")
    op.execute(
        f"CREATE POLICY token_usage_self ON token_usage "
        f"FOR ALL USING (user_id = {_GUC}) WITH CHECK (user_id = {_GUC})"
    )


def downgrade() -> None:
    for table, policies in (
        ("users", ("users_select_all", "users_insert_open", "users_update_self", "users_delete_self")),
        ("api_keys", ("api_keys_select_all", "api_keys_insert_self", "api_keys_update_self", "api_keys_delete_self")),
        ("token_usage", ("token_usage_self",)),
    ):
        for p in policies:
            _drop_policy(table, p)
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
