"""day3_auth

Revision ID: 51d59ebea874
Revises: 001_baseline
Create Date: 2026-04-26 23:44:44.944030+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51d59ebea874'
down_revision: Union[str, None] = '001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_keys', 'scopes',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               nullable=True)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_api_keys_hash'), table_name='api_keys')
    op.drop_index(op.f('idx_api_keys_user_id'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.drop_constraint(op.f('api_keys_user_id_fkey'), 'api_keys', type_='foreignkey')
    op.drop_table_comment(
        'api_keys',
        existing_comment='Named API keys per user. key_hash is SHA-256 of the raw key. Raw key returned exactly once at creation; never stored in plain text.',
        schema=None
    )
    op.alter_column('engrams', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('engrams', 'engram_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.alter_column('engrams', 'distilled_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('engrams', 'actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('engrams', 'objects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('engrams', 'entities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('engrams', 'negated_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('engrams', 'salience_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('engrams', 'connections',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('engrams', 'source_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('engrams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_engrams_created_at'), table_name='engrams')
    op.drop_index(op.f('idx_engrams_engram_id'), table_name='engrams')
    op.drop_index(op.f('idx_engrams_user_id'), table_name='engrams')
    op.create_index(op.f('ix_engrams_created_at'), 'engrams', ['created_at'], unique=False)
    op.create_index(op.f('ix_engrams_engram_id'), 'engrams', ['engram_id'], unique=False)
    op.create_index(op.f('ix_engrams_user_id'), 'engrams', ['user_id'], unique=False)
    op.drop_table_comment(
        'engrams',
        existing_comment='Compressed memory units produced by EngramProcessor. dense_embedding column populated in Day 4 (all-MiniLM-L6-v2, 384-dim).',
        schema=None
    )
    op.alter_column('episodic_memory', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('episodic_memory', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('episodic_memory', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('episodic_memory', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('episodic_memory', 'store_episodic',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('episodic_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_episodic_app_id'), table_name='episodic_memory')
    op.drop_index(op.f('idx_episodic_timestamp'), table_name='episodic_memory')
    op.drop_index(op.f('idx_episodic_user_id'), table_name='episodic_memory')
    op.create_index(op.f('ix_episodic_memory_app_id'), 'episodic_memory', ['app_id'], unique=False)
    op.create_index(op.f('ix_episodic_memory_user_id'), 'episodic_memory', ['user_id'], unique=False)
    op.drop_table_comment(
        'episodic_memory',
        existing_comment='Episodic memory: time-stamped conversation history. Retention enforced by a scheduled cleanup job (default 30 days).',
        schema=None
    )
    op.alter_column('knowledge_edges', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_edges', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=False)
    op.alter_column('knowledge_edges', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('knowledge_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_knowledge_edge_from'), table_name='knowledge_edges')
    op.drop_index(op.f('idx_knowledge_edge_to'), table_name='knowledge_edges')
    op.drop_index(op.f('idx_knowledge_edge_user_id'), table_name='knowledge_edges')
    op.create_index(op.f('ix_knowledge_edges_user_id'), 'knowledge_edges', ['user_id'], unique=False)
    op.drop_table_comment(
        'knowledge_edges',
        existing_comment='Associative memory: knowledge graph edges. Never auto-deleted.',
        schema=None
    )
    op.drop_column('knowledge_edges', 'app_id')
    op.alter_column('knowledge_nodes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('knowledge_nodes', 'store_associative',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_knowledge_node_label'), table_name='knowledge_nodes', postgresql_ops={'label': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_knowledge_node_type'), table_name='knowledge_nodes')
    op.drop_index(op.f('idx_knowledge_node_user_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('idx_knowledge_nodes_app_id'), table_name='knowledge_nodes')
    op.create_index(op.f('ix_knowledge_nodes_app_id'), 'knowledge_nodes', ['app_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_user_id'), 'knowledge_nodes', ['user_id'], unique=False)
    op.drop_table_comment(
        'knowledge_nodes',
        existing_comment='Associative memory: knowledge graph nodes. Never auto-deleted.',
        schema=None
    )
    op.alter_column('procedural_memory', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('procedural_memory', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('procedural_memory', 'workflows',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('procedural_memory', 'store_procedural',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('procedural_memory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('procedural_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_procedural_user_id'), table_name='procedural_memory')
    op.drop_constraint(op.f('procedural_memory_user_id_key'), 'procedural_memory', type_='unique')
    op.create_index(op.f('ix_procedural_memory_user_id'), 'procedural_memory', ['user_id'], unique=True)
    op.drop_table_comment(
        'procedural_memory',
        existing_comment='Procedural memory: user preferences, settings, and workflows. Never auto-deleted; upsert semantics (one row per user).',
        schema=None
    )
    op.alter_column('semantic_memory', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('semantic_memory', 'embedding_model',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('semantic_memory', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('semantic_memory', 'index_semantic',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('semantic_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_semantic_app_id'), table_name='semantic_memory')
    op.drop_index(op.f('idx_semantic_user_id'), table_name='semantic_memory')
    op.drop_index(op.f('idx_semantic_vector'), table_name='semantic_memory', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_semantic_memory_app_id'), 'semantic_memory', ['app_id'], unique=False)
    op.create_index(op.f('ix_semantic_memory_user_id'), 'semantic_memory', ['user_id'], unique=False)
    op.drop_table_comment(
        'semantic_memory',
        existing_comment='Semantic memory: 1536-dim vector embeddings via text-embedding-3-small. Never auto-deleted; manual removal only.',
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'wallet_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_wallet'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_wallet_address_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='Registered users. Supports email/password and wallet-address auth. Created in Day 2 of the 7-day roadmap sprint.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Registered users. Supports email/password and wallet-address auth. Created in Day 2 of the 7-day roadmap sprint.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_wallet_address_key'), 'users', ['wallet_address'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_wallet'), 'users', ['wallet_address'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'wallet_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'semantic_memory',
        'Semantic memory: 1536-dim vector embeddings via text-embedding-3-small. Never auto-deleted; manual removal only.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_semantic_memory_user_id'), table_name='semantic_memory')
    op.drop_index(op.f('ix_semantic_memory_app_id'), table_name='semantic_memory')
    op.create_index(op.f('idx_semantic_vector'), 'semantic_memory', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_semantic_user_id'), 'semantic_memory', ['user_id'], unique=False)
    op.create_index(op.f('idx_semantic_app_id'), 'semantic_memory', ['app_id'], unique=False)
    op.alter_column('semantic_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('semantic_memory', 'index_semantic',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('semantic_memory', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('semantic_memory', 'embedding_model',
               existing_type=sa.TEXT(),
               server_default=sa.text("'text-embedding-3-small'::text"),
               existing_nullable=False)
    op.alter_column('semantic_memory', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'procedural_memory',
        'Procedural memory: user preferences, settings, and workflows. Never auto-deleted; upsert semantics (one row per user).',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_procedural_memory_user_id'), table_name='procedural_memory')
    op.create_unique_constraint(op.f('procedural_memory_user_id_key'), 'procedural_memory', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_procedural_user_id'), 'procedural_memory', ['user_id'], unique=False)
    op.alter_column('procedural_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('procedural_memory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('procedural_memory', 'store_procedural',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('procedural_memory', 'workflows',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               nullable=True)
    op.alter_column('procedural_memory', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('procedural_memory', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'knowledge_nodes',
        'Associative memory: knowledge graph nodes. Never auto-deleted.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_knowledge_nodes_user_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_app_id'), table_name='knowledge_nodes')
    op.create_index(op.f('idx_knowledge_nodes_app_id'), 'knowledge_nodes', ['app_id'], unique=False)
    op.create_index(op.f('idx_knowledge_node_user_id'), 'knowledge_nodes', ['user_id'], unique=False)
    op.create_index(op.f('idx_knowledge_node_type'), 'knowledge_nodes', ['type'], unique=False)
    op.create_index(op.f('idx_knowledge_node_label'), 'knowledge_nodes', ['label'], unique=False, postgresql_ops={'label': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('knowledge_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'store_associative',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('knowledge_nodes', 'properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('knowledge_nodes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.add_column('knowledge_edges', sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'knowledge_edges',
        'Associative memory: knowledge graph edges. Never auto-deleted.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_knowledge_edges_user_id'), table_name='knowledge_edges')
    op.create_index(op.f('idx_knowledge_edge_user_id'), 'knowledge_edges', ['user_id'], unique=False)
    op.create_index(op.f('idx_knowledge_edge_to'), 'knowledge_edges', ['to_node_id'], unique=False)
    op.create_index(op.f('idx_knowledge_edge_from'), 'knowledge_edges', ['from_node_id'], unique=False)
    op.alter_column('knowledge_edges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('knowledge_edges', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('knowledge_edges', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('1.0'),
               nullable=True)
    op.alter_column('knowledge_edges', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'episodic_memory',
        'Episodic memory: time-stamped conversation history. Retention enforced by a scheduled cleanup job (default 30 days).',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_episodic_memory_user_id'), table_name='episodic_memory')
    op.drop_index(op.f('ix_episodic_memory_app_id'), table_name='episodic_memory')
    op.create_index(op.f('idx_episodic_user_id'), 'episodic_memory', ['user_id'], unique=False)
    op.create_index(op.f('idx_episodic_timestamp'), 'episodic_memory', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_episodic_app_id'), 'episodic_memory', ['app_id'], unique=False)
    op.alter_column('episodic_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('episodic_memory', 'store_episodic',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('episodic_memory', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=True)
    op.alter_column('episodic_memory', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               nullable=True)
    op.alter_column('episodic_memory', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('episodic_memory', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'engrams',
        'Compressed memory units produced by EngramProcessor. dense_embedding column populated in Day 4 (all-MiniLM-L6-v2, 384-dim).',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_engrams_user_id'), table_name='engrams')
    op.drop_index(op.f('ix_engrams_engram_id'), table_name='engrams')
    op.drop_index(op.f('ix_engrams_created_at'), table_name='engrams')
    op.create_index(op.f('idx_engrams_user_id'), 'engrams', ['user_id'], unique=False)
    op.create_index(op.f('idx_engrams_engram_id'), 'engrams', ['engram_id'], unique=False)
    op.create_index(op.f('idx_engrams_created_at'), 'engrams', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('engrams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('engrams', 'source_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('engrams', 'connections',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('engrams', 'salience_scores',
               existing_type=sa.JSON(),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('engrams', 'negated_actions',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('engrams', 'entities',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('engrams', 'objects',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('engrams', 'actions',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('engrams', 'distilled_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('engrams', 'engram_id',
               existing_type=sa.String(length=12),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('engrams', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.create_table_comment(
        'api_keys',
        'Named API keys per user. key_hash is SHA-256 of the raw key. Raw key returned exactly once at creation; never stored in plain text.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('api_keys_user_id_fkey'), 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.create_index(op.f('idx_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('idx_api_keys_hash'), 'api_keys', ['key_hash'], unique=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('api_keys', 'scopes',
               existing_type=sa.String(),
               server_default=sa.text("'read,write'::text"),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    # ### end Alembic commands ###
