"""Compatibility no-op for an old autogenerated auth revision.

Revision ID: 51d59ebea874
Revises: 001_baseline
Create Date: 2026-04-26 23:44:44.944030+00:00
"""

from typing import Sequence, Union

revision: str = "51d59ebea874"
down_revision: Union[str, None] = "001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
